### ISSUE TITLE
avutil missing

### ISSUE THREAD

**Issue by christianfrei** [silvanheller/cineast#40]
@lucaro any clue what causes this?

11:09:10.057 [Thread-2] INFO  org.vitrivr.cineast.core.config.Config - config loaded
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/BridJExtractedLibraries539660464557911178/libbridj.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Sep 14, 2016 11:09:10 AM org.bridj.BridJ log
INFORMATION: Library not found : avutil
# BridJ: dlopen error when loading avutil : avutil: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

Sep 14, 2016 11:09:10 AM org.libav.bridge.LibraryManager getInstance
SCHWERWIEGEND: unable to load native libraries
java.io.FileNotFoundException: Library 'avutil' was not found in path '[libav, null, ., /home/christian/bin, /home/christian/.local/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /snap/bin, /usr/java/packages/lib/amd64, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib, /usr/lib/jvm/java-8-openjdk-amd64/jre/bin, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib64, /lib64, /usr/lib, /lib, /usr/local/lib]'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:924)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:901)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:513)
    at org.libav.avutil.bridge.AVUtilLibrary.<init>(AVUtilLibrary.java:61)
    at org.libav.bridge.LibraryManager.<init>(LibraryManager.java:71)
    at org.libav.bridge.LibraryManager.getInstance(LibraryManager.java:141)
    at org.libav.avformat.FormatContextWrapperFactory.<clinit>(FormatContextWrapperFactory.java:38)
    at org.libav.DefaultMediaReader.<init>(DefaultMediaReader.java:62)
    at org.vitrivr.cineast.core.decode.video.JLibAVVideoDecoder.<init>(JLibAVVideoDecoder.java:57)
    at org.vitrivr.cineast.core.config.DecoderConfig.newVideoDecoder(DecoderConfig.java:49)
    at org.vitrivr.cineast.core.run.ExtractionJobRunner.run(ExtractionJobRunner.java:418)
    at java.lang.Thread.run(Thread.java:745)

Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
    at org.libav.DefaultMediaReader.<init>(DefaultMediaReader.java:62)
    at org.vitrivr.cineast.core.decode.video.JLibAVVideoDecoder.<init>(JLibAVVideoDecoder.java:57)
    at org.vitrivr.cineast.core.config.DecoderConfig.newVideoDecoder(DecoderConfig.java:49)
    at org.vitrivr.cineast.core.run.ExtractionJobRunner.run(ExtractionJobRunner.java:418)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.libav.avformat.FormatContextWrapperFactory.<clinit>(FormatContextWrapperFactory.java:38)
    ... 5 more

**Comment by silvanheller** [comment]
Especially since nothing in the build.gradle looks like it's loading that library

**Comment by lucaro** [comment]
JLibAV has native dependencies which need to be present in order for the video decoder to work. What operating system (version) are you using?

**Comment by christianfrei** [comment]
linux-x86_64 Ubuntu

**Comment by lucaro** [comment]
which Ubuntu?

**Comment by christianfrei** [comment]
Ubuntu 16.04.1 LTS

**Comment by lucaro** [comment]
hmm, too bad, the video decoder is not compatible with the libav/ffmpeg version bundled with 16.04. On 14.04 it would have been sufficient to install the following packages:
```libavcodec-dev libavutil-dev libswscale-dev libavformat-dev libavresample-dev```
but in 16.04 they are to new for the library which has not been updated in a while. You can install them anyway, when you do it will give you more information about the expected version of the needed libraries. You will have to provide them in your class path in order for the extraction to work.

**Comment by christianfrei** [comment]
ok I will try it. Thank you!

**Comment by silvanheller** [comment]
Closing

**Comment by silvanheller** [comment]
Reopening Issue since it doesn't work on a fresh install 16.04

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unsupported version of the avutil native library. (51.x.x <= required <= 52.x.x, found 54.31.100)
	at org.libav.avutil.bridge.AVUtilLibrary.<init>(AVUtilLibrary.java:75)
	at org.libav.bridge.LibraryManager.<init>(LibraryManager.java:71)
	at org.libav.bridge.LibraryManager.getInstance(LibraryManager.java:141)
	at org.libav.avformat.FormatContextWrapperFactory.<clinit>(FormatContextWrapperFactory.java:38)
	at org.libav.Default

**Comment by lucaro** [comment]
Yes, as stated in my reply from September 14th, JLibav is quite old and no longer compatible with the libraries shipped with ubuntu 16.04. There is not really much that can be done about this short of adopting the JLibav project, which is not a viable option. To overcome this problem, I added an ffmpeg-based decoder which should work just fine...

**Comment by silvanheller** [comment]
There is a new Bridge here: https://code.google.com/archive/p/jlibav/ which has the following dependency: https://mvnrepository.com/artifact/com.nativelibs4java/bridj/0.7.0. However, this breaks the whole Decoder

**Comment by lucaro** [comment]
The version of jlibav used (0.2.1) is the most recent one. The project is simply not updated anymore (https://github.com/operutka/jlibav/issues/2) and sadly no longer compatible with the current libav/ffmpeg API.

**Comment by silvanheller** [comment]
The FFMPEG Decoder works, thank you!
